name: queries_impl_annotation
description: A package for annotations used by queries_impl_generator package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  failures:
    git: https://github.com/mahmood1996/failures.git
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
